### PR TITLE
Update dependencies prior to Wegue v2

### PR DESCRIPTION
**Pull request by spwoodcock**
Updated any remaining non-dev dependencies, on top of all previous PRs in the V2 series.
Replaces #295.

I can't run the Karma tests easily on my system & don't have time for a workaround right now.
It would be worth running `npm run test` after all the updates.

### CODE REVIEW

**Comment by chrismayer** [comment]
I just checked out the changeset of this PR and created a new Wegue app with `npm run init:app`. Unfortunately this layout seems to be a bit off. There seems to be an Element (white) on top of the map, which shifts down the map itself:

image

Also for the sidebar layout:

image

**Comment by spwoodcock** [comment]
Thanks @chrismayer for the feedback - a bit silly of me - perhaps these are changes introduced by the Vuetify upgrade. I will test further next week and update 👍

**Comment by spwoodcock** [comment]
Found the issue in custom css for AppLogo.vue:

```css
  .v-avatar.v-avatar--tile.wgu-app-logo {
    position: absolute;
    z-index: 2;
  }
```

Should be replace with:

```css
  .v-avatar.wgu-app-logo {
    position: absolute;
    z-index: 2;
  }
```

And the prop `rounded="0"` passed to v-avatar to have a square tile.

I will update all PRs.

**Comment by spwoodcock** [comment]
I also updated some other minor deprecations from Vuetify 2.2.x --> 2.3.x in commit https://github.com/wegue-oss/wegue/pull/333/commits/42ead057b461b77b84e6875800ee6d1ef7fd3ea0

There were no relevant upgrades from 2.3.x --> 2.4.x and no upgrades at all from 2.4.x --> 2.6.x (LTS).

I cherry-picked the commit onto all subsequent stacked PRs.

**Comment by spwoodcock** [comment]
It should also be noted that all edits in https://github.com/wegue-oss/wegue/commit/42ead057b461b77b84e6875800ee6d1ef7fd3ea0 were to the components directory, so no manual updates during the V1 --> V2 upgrade should be required.

There is however one minor deprecation to the `app-starter`, found in commit https://github.com/wegue-oss/wegue/pull/335/commits/a12cd0d4dcf7d79c7ac8e67a3152768aa1b15519:

The update is a very simple on for `WguAppTemplate.vue`.

```
<v-content app>
...
<v-content />
```
to
```
<v-main app>
...
<v-main />
```

**This should probably be noted for any upgrade guide we may include for users migrating apps V1 -> V2.**

**Comment by chrismayer** [comment]
I just pulled your updates and changed `<v-content>` to `<v-main>` in `WguAppTemplate.vue`. Now everything looks good to me:

image

Very nice! Thanks again.

**Comment by chrismayer** [comment]
@spwoodcock Would you mind resolving the conflict, so this PR gets mergable again? In my point of view the base PR #320 also has the conflict and should be an whitespace change only.

**Review by chrismayer — APPROVED** [review]

**Comment by fschmenger** [comment]
Hi @spwoodcock, thanks for your ongoing efforts!
It looks like the merge in 6d9c8579a6b7cdee5be773e61024a2af143274b4 has gone the wrong way, as a lot of those methods in AttributeTable were removed in the master (see 3d7116395049b1f03a640824b0fb0a9511e8107e)
Sorry for the brief comment, these are currently busy days for me but I hope I can test it more throughoutly in the upcoming weeks.
Cheers, Felix

**Comment by spwoodcock** [comment]
Hey @fschmenger sorry about the notifications - I was testing to see what would fix the conflicts, as I didn't want to rebase the entire branch again.

I ended up just checking out the `master` for the files, as they are only whitespace related.

Please check everything is all good 👍

**Comment by spwoodcock** [comment]
Cherry-picked 23c9451d425646de04879c00e66850f91869d13e to make this mergable.

**Comment by spwoodcock** [comment]
Merged `master` to only show specific commits - ready to test and merge.

**Comment by chrismayer** [comment]
Thanks for merging in the current master @spwoodcock.

Unfortunately the unit tests in the CI fail. Not sure if this was the case before the merge or if they were OK before. They also fail for #333 and #334 and it is locally reproducible when you execute `npm run test` with the code of this PR.

I did a fresh checkout of the code of this PR and created the Wegue example apps. There are some linting problems in the `AttributeTableWin` component, which can easily be fixed with this [commit](https://github.com/wegue-oss/wegue/commit/e2e18cd748786957a50409a4950d72d5acda7ae7).

After that everything worked as expected at least as far as I could see in some visual tests by clicking through the modules in the example apps.

**Comment by spwoodcock** [comment]
Thanks @chrismayer!

Apologies for not being very thorough and checking the tests after merge - I'm also pretty pushed for time currently.

We planned to use Wegue as our geospatial module in EnviDat/WSL in CH, but I am leaving and priorities have shifted for now.

I'll make contributions to fix these PRs and add cloud native format support (COG, flatgeobuf, geoparquet, COPC) in the near future.

**Comment by chrismayer** [comment]
@spwoodcock I had a look at the test suite and why it is failing. This [commit](https://github.com/chrismayer/wegue/commit/dca35514fa0ee83b365cc7e0fb99e877aca7ad8c) should fix it. Are you willing to pull it into this PR or should I open a new PR based on this PR with the additional fix?

**Comment by spwoodcock** [comment]
Much appreciated @chrismayer! I added the commit =)

**Comment by chrismayer** [comment]
So I did some more tests by upgrading a current application to this branch and it works very well. No problems so far, so I finally will merge this :tada:

If any problems will occur afterwards we will handle them in follow-up PRs as always.

I also will come up with an update of the migration guide and I am going to update the v2 roadmap (#327).

Thanks again to all, who were involved. This is another great step forward :+1:

**Pull request merged**
