### PR TITLE
Update main deps

### PR DESCRIPTION
**Pull request by chrismayer**
Updates the main base libs to the current (non-breaking) versions:

- OpenLayers v6.2.1
- Vue v2.6.11
- Vuetify v1.5.23

### CODE REVIEW

**Comment by justb4** [comment]
Do you plan to upgrade to Vuetify v2 (2.2.15 is now stable release)? Will have some impact (did the same in a much smaller Vue app, but new syntax is cleaner), but in longer term is better now that there are not too many widgets. Or could be done in separate PR. Even v3 (Vue3) is planned for this year.

**Comment by chrismayer** [comment]
There are no plans so far about upgrading to Vuetify v2 and / or Vue v3 from my side. But if someone volunteers, why not...

**Comment by JakobMiksch** [comment]
Tested it on my computer. All features seem to work like expected

**Comment by chrismayer** [comment]
Thanks for the review, @JakobMiksch! I'll merge now.

**Comment by justb4** [comment]
Also merged/pushed this my local branch ok.

**Pull request merged**
